"""RPA Fargate + Step Functions + per-org EventBridge schedule.

This component owns everything the RPA integration needs at runtime:

  * a small VPC (private subnets with NAT) for the Fargate task to
    reach the vendor portal and the AWS endpoints it talks to;
  * an ECS cluster + Fargate task definition + a Docker image built
    from `fargate/rpa_runner/Dockerfile` (CDK builds + pushes via
    DockerImageAsset);
  * a Step Functions state machine that wraps `RunTask` so per-run
    state is visible in the SFN console and the existing
    org-not-configured / no-credentials failure modes get clear
    failure states without conflating with Fargate retry policy;
  * one EventBridge rule per opted-in org targeting the state
    machine with the org's cron and `organization_id` in the input.

Anti-features (deliberate omissions):

  * No automatic retry on the Fargate task. A failed run = clean
    audit row + a fresh run at the next scheduled tick. Blanket
    retrying a browser-automation task burns the rate limit and
    looks like brute force to the target portal.

  * No shared per-run state. Each Fargate task starts cold,
    re-authenticates, and runs to completion. JWT + session cookie
    never persist between runs (see lambda/multi-org/rpa/oauth flow).

  * No per-org Fargate cluster. One cluster runs all orgs' tasks;
    the task input identifies the org, and the runner reads the
    matching `RPA_CONFIG` from DynamoDB.

The admin Lambda (admin_ui.py) is the only Lambda that talks to the
state machine — it triggers manual runs and reads execution status
through `rpa_api.py`. The wiring `RPA_STATE_MACHINE_ARN` env var +
`states:StartExecution` / `ListExecutions` / `DescribeExecution`
grants is done in admin_ui.py (out-of-band addition: see
penguin_health_stack.py).
"""

from __future__ import annotations

from pathlib import Path

from aws_cdk import (
    Duration,
    RemovalPolicy,
    aws_ec2 as ec2,
    aws_ecr_assets as ecr_assets,
    aws_ecs as ecs,
    aws_events as events,
    aws_events_targets as targets,
    aws_iam as iam,
    aws_logs as logs,
    aws_stepfunctions as sfn,
    aws_stepfunctions_tasks as sfn_tasks,
)
from constructs import Construct

import config


# Per-org schedules. The list lives here (not in DynamoDB) because each
# entry produces a CDK resource (EventBridge rule) that CloudFormation
# needs to know about at deploy time. Adding an org = one entry here +
# the per-org config seed scripts in scripts/multi-org/.
#
# Cron expressions follow EventBridge format (NOT crontab). Common slots:
#   "cron(0 22 * * ? *)"     daily at 22:00 UTC
#   "cron(0/30 * * * ? *)"   every 30 min
#
# The Step Functions input merges this `organization_id` with a fresh
# `run_id` generated by the SFN itself (see `_build_state_machine`).
_PER_ORG_SCHEDULES: list[dict] = [
    # {"org_id": "demo", "cron": "cron(0 22 * * ? *)"},
    # Disabled by default. Onboarding flow:
    #   1. seed RPA_CONFIG + credentials secret + playbook
    #   2. add an entry here, redeploy
    #   3. monitor first runs in Step Functions console
]


class Rpa(Construct):

    def __init__(self, scope: Construct, construct_id: str, *,
                 org_config_table) -> None:
        super().__init__(scope, construct_id)

        # ----- VPC ------------------------------------------------------
        # Two AZs is the minimum Fargate accepts; private subnets with
        # NAT give the task outbound HTTPS to the vendor portal + AWS
        # APIs without an inbound surface. No public subnets — we never
        # accept inbound traffic on the runner.
        self.vpc = ec2.Vpc(
            self, "RpaVpc",
            ip_addresses=ec2.IpAddresses.cidr("10.40.0.0/16"),
            max_azs=2,
            nat_gateways=1,
            subnet_configuration=[
                ec2.SubnetConfiguration(
                    name="rpa-public",
                    subnet_type=ec2.SubnetType.PUBLIC,
                    cidr_mask=24,
                ),
                ec2.SubnetConfiguration(
                    name="rpa-private",
                    subnet_type=ec2.SubnetType.PRIVATE_WITH_EGRESS,
                    cidr_mask=24,
                ),
            ],
        )

        # ----- ECS cluster ---------------------------------------------
        self.cluster = ecs.Cluster(
            self, "RpaCluster",
            cluster_name=f"{config.PROJECT_NAME}-rpa",
            vpc=self.vpc,
            container_insights_v2=ecs.ContainerInsights.ENABLED,
        )

        # ----- Container image -----------------------------------------
        # CDK builds + pushes the image at deploy time. The build context
        # is the repo root because the Dockerfile copies from both
        # `fargate/rpa_runner/` and `lambda/multi-org/`.
        repo_root = Path(__file__).resolve().parents[2]
        self.image_asset = ecr_assets.DockerImageAsset(
            self, "RpaRunnerImage",
            directory=str(repo_root),
            file="fargate/rpa_runner/Dockerfile",
            # Pin the build platform so a developer on Apple Silicon
            # doesn't ship an arm64 image to an x86_64 task.
            platform=ecr_assets.Platform.LINUX_AMD64,
        )

        # ----- Task IAM roles ------------------------------------------
        # Execution role: pull from ECR, write logs. The CDK pattern is
        # to let `FargateTaskDefinition` create this and add managed
        # policies; we attach the ECR + logs grants below.
        self.task_role = iam.Role(
            self, "RpaTaskRole",
            assumed_by=iam.ServicePrincipal("ecs-tasks.amazonaws.com"),
            description="Penguin Health RPA runner task role",
        )

        # DDB: read RPA_CONFIG + RPA_PLAYBOOK#* items (no writes).
        org_config_table.grant_read_data(self.task_role)

        # Secrets Manager: only the per-org credentials secret.
        # Wildcard scoped to the `/rpa/*/credentials` path so a
        # compromised runner cannot read e.g. Stedi's API key.
        self.task_role.add_to_policy(iam.PolicyStatement(
            actions=["secretsmanager:GetSecretValue"],
            resources=[
                f"arn:aws:secretsmanager:{config.AWS_REGION}:*:secret:"
                f"penguin-health/rpa/*/credentials-*",
            ],
        ))

        # S3: PutObject to any per-org bucket under data/*. Mirrors the
        # existing wildcard in audit_engine.py — we don't broaden it,
        # just reuse the same pattern.
        self.task_role.add_to_policy(iam.PolicyStatement(
            actions=["s3:PutObject"],
            resources=[
                f"arn:aws:s3:::{config.PROJECT_NAME}-*/data/*",
            ],
        ))

        # Audit emitter writes to the audit DDB table + Firehose. Both
        # are owned by AuditLayer; the import-time emit cannot know the
        # ARNs, so AuditLayer reaches in via the `emitting_fns` list
        # for Lambdas. For Fargate we add the grants here using the
        # known resource ARNs (table + firehose), referenced through
        # the env vars the runner reads at startup.
        self.task_role.add_to_policy(iam.PolicyStatement(
            actions=["dynamodb:PutItem"],
            resources=[
                f"arn:aws:dynamodb:{config.AWS_REGION}:*:table/"
                f"{config.PROJECT_NAME}-audit",
            ],
        ))
        self.task_role.add_to_policy(iam.PolicyStatement(
            actions=["firehose:PutRecord", "firehose:PutRecordBatch"],
            resources=[
                f"arn:aws:firehose:{config.AWS_REGION}:*:deliverystream/"
                f"{config.PROJECT_NAME}-audit",
            ],
        ))

        # EventBridge: PutEvents for the RpaIngestComplete signal.
        self.task_role.add_to_policy(iam.PolicyStatement(
            actions=["events:PutEvents"],
            resources=[
                f"arn:aws:events:{config.AWS_REGION}:*:event-bus/default",
            ],
        ))

        # CloudWatch metrics namespace for runner-side counters.
        self.task_role.add_to_policy(iam.PolicyStatement(
            actions=["cloudwatch:PutMetricData"],
            resources=["*"],
            conditions={
                "StringEquals": {
                    "cloudwatch:namespace": "PenguinHealth/Rpa",
                },
            },
        ))

        # ----- Task definition -----------------------------------------
        self.log_group = logs.LogGroup(
            self, "RpaRunnerLogs",
            log_group_name=f"/aws/ecs/{config.PROJECT_NAME}-rpa-runner",
            retention=logs.RetentionDays.THREE_MONTHS,
            removal_policy=RemovalPolicy.RETAIN,
        )

        # Playwright + Chromium are memory-hungry; 2 vCPU / 4 GB is the
        # comfortable floor. Stay under the 6 GB / 2 vCPU step so cost
        # stays predictable.
        self.task_definition = ecs.FargateTaskDefinition(
            self, "RpaRunnerTaskDef",
            cpu=2048,
            memory_limit_mib=4096,
            task_role=self.task_role,
            family=f"{config.PROJECT_NAME}-rpa-runner",
        )

        self.container = self.task_definition.add_container(
            "runner",
            image=ecs.ContainerImage.from_docker_image_asset(self.image_asset),
            logging=ecs.LogDriver.aws_logs(
                stream_prefix="run",
                log_group=self.log_group,
            ),
            environment={
                "ORG_CONFIG_TABLE_NAME": org_config_table.table_name,
                "AUDIT_TABLE_NAME": f"{config.PROJECT_NAME}-audit",
                "AUDIT_FIREHOSE_NAME": f"{config.PROJECT_NAME}-audit",
            },
            # ORG_ID, RUN_ID, MODE are injected per-execution by the
            # Step Functions task below via container overrides.
        )

        # ----- Step Functions state machine ----------------------------
        self.state_machine = self._build_state_machine()

        # ----- Per-org EventBridge schedules ---------------------------
        # One rule per org so each can have its own cron + can be
        # paused independently (`enabled=False` on the rule).
        for entry in _PER_ORG_SCHEDULES:
            org_id = entry["org_id"]
            rule = events.Rule(
                self, f"RpaSchedule{_safe_id(org_id)}",
                rule_name=f"{config.PROJECT_NAME}-rpa-{org_id}",
                schedule=events.Schedule.expression(entry["cron"]),
                description=f"RPA scheduled run for org {org_id}",
                enabled=entry.get("enabled", True),
            )
            rule.add_target(targets.SfnStateMachine(
                self.state_machine,
                input=events.RuleTargetInput.from_object({
                    "organization_id": org_id,
                    "mode": "scheduled",
                }),
            ))

    # ------------------------------------------------------------------
    # Internals
    # ------------------------------------------------------------------

    def _build_state_machine(self) -> sfn.StateMachine:
        """Run the Fargate task with org-scoped input.

        State diagram:

            Start
              -> GenerateRunId  (Pass: mints `run-{uuid}` if not provided)
              -> RunTask        (ECS RunTask, sync)
              -> Succeed

        Any failure inside RunTask flows through the state machine's
        CloudWatch logs + execution history; the runner itself emits
        a `RpaPlaybookRun major-failure` audit before exiting non-zero,
        so the SFN console + the audit DDB are the two source-of-truth
        surfaces.
        """
        # Pass state synthesizes a run_id if the caller didn't pass one.
        # EventBridge-scheduled invocations do not pass run_id; the
        # admin-Lambda manual-trigger does (and overrides this).
        generate_run_id = sfn.Pass(
            self, "GenerateRunId",
            parameters={
                "organization_id.$": "$.organization_id",
                "mode.$": "$.mode",
                "run_id.$": "States.Format('run-{}', States.UUID())",
            },
        )

        # Choice: prefer the input's run_id if present (manual trigger),
        # else use the generated one.
        choose_run_id = sfn.Choice(self, "RunIdProvided?")
        passthrough = sfn.Pass(
            self, "UseProvidedRunId",
            parameters={
                "organization_id.$": "$.organization_id",
                "mode.$": "$.mode",
                "run_id.$": "$.run_id",
            },
        )

        run_task = sfn_tasks.EcsRunTask(
            self, "RunFargateTask",
            integration_pattern=sfn.IntegrationPattern.RUN_JOB,
            cluster=self.cluster,
            task_definition=self.task_definition,
            launch_target=sfn_tasks.EcsFargateLaunchTarget(
                platform_version=ecs.FargatePlatformVersion.LATEST,
            ),
            # Subnets: private only — never give the runner a public IP.
            subnets=ec2.SubnetSelection(
                subnet_type=ec2.SubnetType.PRIVATE_WITH_EGRESS,
            ),
            assign_public_ip=False,
            container_overrides=[
                sfn_tasks.ContainerOverride(
                    container_definition=self.container,
                    environment=[
                        sfn_tasks.TaskEnvironmentVariable(
                            name="ORG_ID", value=sfn.JsonPath.string_at(
                                "$.organization_id")),
                        sfn_tasks.TaskEnvironmentVariable(
                            name="RUN_ID", value=sfn.JsonPath.string_at(
                                "$.run_id")),
                        sfn_tasks.TaskEnvironmentVariable(
                            name="MODE", value=sfn.JsonPath.string_at(
                                "$.mode")),
                    ],
                ),
            ],
            result_path=sfn.JsonPath.DISCARD,
        )

        succeed = sfn.Succeed(self, "Done")

        # Wire: choice -> (manual: passthrough | scheduled: generate) -> run_task -> succeed
        choose_run_id.when(
            sfn.Condition.is_present("$.run_id"),
            passthrough.next(run_task),
        )
        choose_run_id.otherwise(generate_run_id.next(run_task))
        run_task.next(succeed)

        return sfn.StateMachine(
            self, "RpaStateMachine",
            state_machine_name=f"{config.PROJECT_NAME}-rpa-run",
            definition_body=sfn.DefinitionBody.from_chainable(choose_run_id),
            timeout=Duration.minutes(30),
            tracing_enabled=True,
        )


def _safe_id(org_id: str) -> str:
    """CloudFormation logical IDs are alphanumeric only."""
    return "".join(c for c in org_id.title() if c.isalnum()) or "Default"
