"""
Tool implementations for the NL Explorer agent loop.

Each tool is a pair:
  - SCHEMA: a Bedrock tool-use schema (name, description, input_schema)
  - a callable invoked by nl_agent.run_agent_loop with the tool's input dict

The tools share the same org_id + a NarrativeExtractor callable so the
agent worker can wire concurrency / retries / Bedrock auth at construction
time and the tools themselves stay pure.

The S3-spill helper is used by `run_sql` and `extract_from_rows` to keep
large row payloads out of the DynamoDB job item (400KB cap). Trace entries
carry an `output_s3_key` pointer when the payload spilled.
"""

import json
import os
import time
import uuid
from concurrent.futures import ThreadPoolExecutor
from typing import Callable, Optional

import analytics_helpers
from audit import SystemPrincipal, emit as audit_emit

_AUDIT_PRINCIPAL = SystemPrincipal(
    os.environ.get('AWS_LAMBDA_FUNCTION_NAME', 'admin-api-nl-agent')
)


# Bytes threshold above which we spill a tool output to S3 instead of
# echoing it through DynamoDB. Tuned so a 100-row, 5-col result stays
# inline but a 200-row scope with narratives spills.
SPILL_THRESHOLD_BYTES = 10_000

# Max rows the agent may pass to extract_from_rows in a single call.
# Each row triggers one Bedrock call; the handler fans out 10-way so 500
# rows is ~50-150s of wall time, well inside the 10-min worker ceiling.
# When a question genuinely exceeds this, the agent can batch via
# repeated run_sql calls (OFFSET/LIMIT) and union the results with
# concat_runs. Decoupled from MAX_DEEP_SCOPE_LIMIT (legacy deep mode)
# so the two surfaces can evolve independently.
MAX_EXTRACT_ROWS = 500

# How many rows of a run_sql / extract result to include inline as a
# "preview" so the agent can sanity-check the shape without dumping the
# full payload into the prompt. Full rows live in the run cache, keyed
# by run_id, and downstream tools fetch them by id.
PREVIEW_ROWS = 5


class RunCache:
    """In-memory cache of intermediate tool results keyed by run_id.

    Exists for the lifetime of one agent worker invocation. The reason it
    exists at all: tool-use loops are unreliable at copying structured row
    data verbatim between tool calls (the model omits, summarizes, or
    hallucinates). Returning a short run_id and letting downstream tools
    reference it by id eliminates the copy entirely.

    Rows are stored as a list of dicts (column-name keyed). run_sql output
    is converted on insert; extract/aggregate output is already in that
    shape.
    """

    def __init__(self):
        self._runs: dict = {}
        self._seq = 0

    def put(self, kind: str, columns: list, rows: list, meta: Optional[dict] = None) -> str:
        self._seq += 1
        run_id = f"{kind}-{self._seq:03d}"
        self._runs[run_id] = {
            "columns": columns,
            "rows": rows,
            "meta": meta or {},
        }
        return run_id

    def get(self, run_id: str) -> Optional[dict]:
        return self._runs.get(run_id)


def _positional_rows_to_dicts(columns: list, rows: list) -> list:
    """Convert run_sql's positional row shape ([[v1, v2], ...]) into the
    column-keyed dict shape ([{col1: v1, col2: v2}, ...]) downstream tools
    expect. Idempotent: if rows already look like dicts, returns them
    unchanged.
    """
    if not rows:
        return []
    if isinstance(rows[0], dict):
        return rows
    col_names = [c.get("name") if isinstance(c, dict) else str(c) for c in columns]
    return [
        {name: (row[i] if i < len(row) else None) for i, name in enumerate(col_names)}
        for row in rows
    ]


# ---- Bedrock tool schemas ---------------------------------------------

INSPECT_SCHEMA_TOOL = {
    "name": "inspect_schema",
    "description": (
        "Return the chart + validation table schemas for this org. "
        "Each column entry may include: `role` (e.g. clinical_date, "
        "narrative_prose, boolean_flag, monetary_amount), observed "
        "`values` for enums/flags, `notes` with format/cast guidance, "
        "and `do_not_use_for` when the column name is misleading. The "
        "top-level response may also include `row_grain` (what one row "
        "represents), `column_groups` (clusters of related columns with "
        "a `primary` to default to), and `join_keys` (columns that "
        "identify a unique patient/visit/plan). Call this ONCE at the "
        "start — the metadata it returns prevents most schema-related "
        "errors. Roles, values, and do_not_use_for were generated by "
        "auditing real data, so trust them over name-based guesses."
    ),
    "input_schema": {"type": "object", "properties": {}, "additionalProperties": False},
}

RUN_SQL_TOOL = {
    "name": "run_sql",
    "description": (
        "Execute an Athena SELECT against the org's analytics tables. "
        "SQL is validated (SELECT-only, table allowlist) and a LIMIT is "
        "injected if absent. Returns "
        "{run_id, columns, preview_rows, row_count, sql}. The FULL rows "
        "are held server-side under run_id; downstream tools "
        "(extract_from_rows, aggregate) accept `from_run_id` so you "
        "never need to copy rows into their inputs."
    ),
    "input_schema": {
        "type": "object",
        "properties": {
            "sql": {"type": "string", "description": "Athena/Presto SELECT statement."},
        },
        "required": ["sql"],
        "additionalProperties": False,
    },
}

EXTRACT_FROM_ROWS_TOOL = {
    "name": "extract_from_rows",
    "description": (
        "Per-row Claude extraction of a short string from narrative "
        "fields. Use this when an answer is buried in prose and cannot "
        "be filtered with SQL LIKE. Cap: 200 rows per call.\n\n"
        "PREFERRED: pass `from_run_id` with the run_id you got from "
        "run_sql. The server pulls the rows from cache; you don't need "
        "to copy them into the input. Example: "
        '{"from_run_id": "sql-001", "question": "What agency referred?"}.\n'
        "Alternative (only for small literal data): pass `rows` as an "
        'array of column-keyed objects, e.g. [{"clientvisit_id": "abc", '
        '"answer": "text..."}].\n\n'
        "Returns {run_id, row_count, preview_results}. The output rows "
        "preserve EVERY source-row field (e.g. clientvisit_id, answer) "
        "AND add `extracted_value` — so you do NOT need to merge the "
        "extraction back to the source. Just pass the extract run_id "
        "straight to aggregate, select_columns, or finalize."
    ),
    "input_schema": {
        "type": "object",
        "properties": {
            "from_run_id": {
                "type": "string",
                "description": (
                    "Server-side row reference returned by a previous "
                    "run_sql call. Strongly preferred over literal `rows`."
                ),
            },
            "rows": {
                "type": "array",
                "description": (
                    "Optional literal rows. Use ONLY when you don't "
                    "already have a run_id (e.g. tiny ad-hoc data). "
                    "Array of column-keyed objects."
                ),
                "items": {"type": "object"},
            },
            "question": {
                "type": "string",
                "description": "What to extract from each row's narrative.",
            },
        },
        "required": ["question"],
        "additionalProperties": False,
    },
}

AGGREGATE_TOOL = {
    "name": "aggregate",
    "description": (
        "Group rows by one or more keys and count or sum. Use this after "
        "extract_from_rows to turn per-row extracted values into a "
        "{value, count} table. Operates in-memory; do NOT re-query Athena.\n\n"
        "PREFERRED: pass `from_run_id` with the run_id from a previous "
        "run_sql or extract_from_rows call. For extract_from_rows output, "
        "group_by typically = [\"extracted_value\"].\n"
        "Alternative: pass `rows` as a literal array of column-keyed objects.\n\n"
        "Returns {run_id, columns, rows, row_count} in positional shape "
        "ready to feed into finalize."
    ),
    "input_schema": {
        "type": "object",
        "properties": {
            "from_run_id": {
                "type": "string",
                "description": (
                    "Server-side row reference. Preferred over literal `rows`."
                ),
            },
            "rows": {
                "type": "array",
                "items": {"type": "object"},
                "description": "Optional literal row objects.",
            },
            "group_by": {
                "type": "array",
                "items": {"type": "string"},
                "description": "Field names to group by.",
            },
            "agg": {
                "type": "string",
                "enum": ["count", "sum"],
                "description": (
                    "Aggregation to apply. 'count' counts rows per group; "
                    "'sum' requires sum_field."
                ),
            },
            "sum_field": {
                "type": "string",
                "description": "Field to sum when agg='sum'.",
            },
            "order_by": {
                "type": "string",
                "enum": ["count_desc", "count_asc", "key_asc"],
                "description": "How to sort the output rows.",
            },
        },
        "required": ["group_by", "agg"],
        "additionalProperties": False,
    },
}

CONCAT_RUNS_TOOL = {
    "name": "concat_runs",
    "description": (
        "Concatenate rows from multiple run_ids (UNION ALL) into a single "
        "new run_id. Use this when a single extract_from_rows call would "
        "exceed the per-call row cap and you've batched it via multiple "
        "run_sql + extract_from_rows pairs. All input runs must share the "
        "same set of column names (order doesn't matter — rows are dict-"
        "keyed). Returns {run_id, columns, row_count} ready for "
        "aggregate / select_columns / finalize."
    ),
    "input_schema": {
        "type": "object",
        "properties": {
            "from_run_ids": {
                "type": "array",
                "items": {"type": "string"},
                "description": (
                    "Two or more run_ids to concatenate, in order. "
                    "Typically all extract-* or all select-* runs from "
                    "a batched workflow."
                ),
            },
        },
        "required": ["from_run_ids"],
        "additionalProperties": False,
    },
}


FILTER_ROWS_TOOL = {
    "name": "filter_rows",
    "description": (
        "Drop rows from a cached run based on a single-column predicate. "
        "Use this to keep only the rows that match an extracted_value, or "
        "to drop nulls before aggregate/finalize. Operates in-memory on "
        "rows already cached under a run_id — does NOT re-query Athena.\n\n"
        "Common pattern: run_sql → extract_from_rows → filter_rows("
        "extracted_value == 'YES') → finalize.\n\n"
        "Supported ops: '==', '!=', 'is_null', 'is_not_null', 'in', 'not_in'. "
        "For 'in' / 'not_in', pass `values` (a list). For '==' / '!=', pass "
        "`value` (a single literal). 'is_null' / 'is_not_null' need neither. "
        "All comparisons are stringified (rows are string-typed)."
    ),
    "input_schema": {
        "type": "object",
        "properties": {
            "from_run_id": {
                "type": "string",
                "description": (
                    "Server-side row reference returned by a previous tool "
                    "(run_sql, extract_from_rows, aggregate, select_columns)."
                ),
            },
            "field": {
                "type": "string",
                "description": "Source column name to test.",
            },
            "op": {
                "type": "string",
                "enum": ["==", "!=", "is_null", "is_not_null", "in", "not_in"],
                "description": "Predicate operator.",
            },
            "value": {
                "description": (
                    "Literal to compare against (for == / !=). String, "
                    "number, or bool. Coerced to string for comparison."
                ),
            },
            "values": {
                "type": "array",
                "items": {},
                "description": "List of literals (for in / not_in).",
            },
        },
        "required": ["from_run_id", "field", "op"],
        "additionalProperties": False,
    },
}


SELECT_COLUMNS_TOOL = {
    "name": "select_columns",
    "description": (
        "Shape the rows behind a run_id into the columns the user asked "
        "for. Pick a subset of existing columns, optionally with a "
        "computed column derived from a CASE-WHEN expression (e.g. "
        "'show answer only when extracted_value == UNKNOWN'). Returns "
        "{run_id, columns, rows, row_count} ready for finalize.\n\n"
        "Use this when you need a final shape that's a strict subset of "
        "an extract_from_rows or run_sql result, or when you need a "
        "conditional column. Do NOT try to encode conditional logic "
        "inside an extract_from_rows prompt — use select_columns.computed."
    ),
    "input_schema": {
        "type": "object",
        "properties": {
            "from_run_id": {
                "type": "string",
                "description": (
                    "Server-side row reference returned by a previous "
                    "tool (run_sql, extract_from_rows, aggregate)."
                ),
            },
            "columns": {
                "type": "array",
                "items": {"type": "string"},
                "description": (
                    "Output column names, in display order. Each name "
                    "must either match a column in the source run_id "
                    "OR be a key in `computed`."
                ),
            },
            "computed": {
                "type": "object",
                "description": (
                    "Optional map of output_column_name -> "
                    "{case_when: {field, op, value, then, else}}. "
                    "`field` is the source column to test; `op` is "
                    "'==' or '!='; `value` is the literal to compare; "
                    "`then` and `else` are EITHER literal strings OR "
                    "names of source columns (looked up if they match)."
                ),
            },
        },
        "required": ["from_run_id", "columns"],
        "additionalProperties": False,
    },
}


FINALIZE_TOOL = {
    "name": "finalize",
    "description": (
        "Emit the final answer to the user. The loop ends after this call. "
        "Choose viz_type based on the shape: 'bar' for categorical counts, "
        "'line' for time series, 'pie' for parts-of-whole with <=8 slices, "
        "'table' otherwise.\n\n"
        "PREFERRED: pass `from_run_id` with the run_id of the result you "
        "want rendered. The server reads the cached columns + rows "
        "directly — you do NOT need to copy them into the input. This is "
        "important: large row payloads (more than ~50 rows) frequently "
        "truncate when the model copies them inline, silently producing "
        "an empty final answer.\n\n"
        "Alternative (for small ad-hoc data): pass literal `columns` and "
        "`rows`. `rows` is positional, parallel to `columns`."
    ),
    "input_schema": {
        "type": "object",
        "properties": {
            "from_run_id": {
                "type": "string",
                "description": (
                    "Server-side row reference returned by a previous tool. "
                    "Strongly preferred over literal columns + rows."
                ),
            },
            "columns": {
                "type": "array",
                "items": {
                    "type": "object",
                    "properties": {
                        "name": {"type": "string"},
                        "type": {"type": "string"},
                    },
                    "required": ["name"],
                },
                "description": (
                    "Optional literal columns. Use ONLY when you don't "
                    "have a run_id (e.g. tiny ad-hoc data). When "
                    "from_run_id is set, the cached columns are used."
                ),
            },
            "rows": {
                "type": "array",
                "items": {"type": "array"},
                "description": (
                    "Optional literal rows, positional and parallel to "
                    "columns. Use ONLY when from_run_id is not set."
                ),
            },
            "viz_type": {
                "type": "string",
                "enum": ["bar", "line", "pie", "table"],
            },
            "explanation": {
                "type": "string",
                "description": "One-sentence summary of how the answer was derived.",
            },
        },
        "required": [],
        "additionalProperties": False,
    },
}


ALL_TOOL_SCHEMAS = [
    INSPECT_SCHEMA_TOOL,
    RUN_SQL_TOOL,
    EXTRACT_FROM_ROWS_TOOL,
    AGGREGATE_TOOL,
    FILTER_ROWS_TOOL,
    SELECT_COLUMNS_TOOL,
    CONCAT_RUNS_TOOL,
    FINALIZE_TOOL,
]


# ---- Tool implementations ---------------------------------------------

def _serialize_columns(schema_cols: list) -> list:
    """Serialize chart/validation column entries for the wire. Includes
    name/type, the narrative flag, the audited role/values/do_not_use_for
    when present, and the human-written notes. Skips fields that are empty
    so the prompt stays compact for the agent."""
    out = []
    for c in schema_cols:
        entry = {"name": c["name"], "type": c["type"]}
        if c.get("narrative"):
            entry["narrative"] = True
        if c.get("role"):
            entry["role"] = c["role"]
        if c.get("values"):
            entry["values"] = c["values"]
        if c.get("notes"):
            entry["notes"] = c["notes"]
        if c.get("do_not_use_for"):
            entry["do_not_use_for"] = c["do_not_use_for"]
        out.append(entry)
    return out


def make_inspect_schema_handler(org_id: str) -> Callable:
    def handler(_input: dict) -> dict:
        schema = analytics_helpers.ORG_SCHEMAS[org_id]
        suffix = analytics_helpers.table_suffix(org_id)
        out = {
            "tables": {
                f"charts_{suffix}": {
                    "columns": _serialize_columns(schema["chart_columns"]),
                    "partition_key": schema.get("chart_partition_key"),
                    "partition_notes": schema.get("chart_partition_notes"),
                },
                f"validation_results_{suffix}": {
                    "columns": _serialize_columns(schema["validation_columns"]),
                    "partition_key": schema.get("validation_partition_key"),
                    "partition_notes": schema.get("validation_partition_notes"),
                },
            },
        }
        # Audited semantic metadata. Only surface non-empty pieces so orgs
        # without an audit JSON still get a tight payload.
        if schema.get("row_grain"):
            out["row_grain"] = schema["row_grain"]
            if schema.get("row_grain_explanation"):
                out["row_grain_explanation"] = schema["row_grain_explanation"]
        if schema.get("column_groups"):
            out["column_groups"] = schema["column_groups"]
        if schema.get("join_keys"):
            jk = {k: v for k, v in schema["join_keys"].items() if v}
            if jk:
                out["join_keys"] = jk
        return out
    return handler


def make_run_sql_handler(
    org_id: str,
    cache: RunCache,
    spill: Optional[Callable[[bytes, str], str]] = None,
) -> Callable:
    """Build the run_sql tool handler for an org.

    Stashes the FULL row data in the worker-local RunCache under a fresh
    run_id and returns only a short preview to Claude. Downstream tools
    (extract_from_rows, aggregate) accept `from_run_id` so the agent
    never has to copy rows between tool calls — which it's bad at.

    spill: optional callable(bytes, suffix_hint) -> s3_key for very large
    results, so the in-memory cache doesn't balloon. The spill key is
    stored in the cache's `meta` so a UI deep-dive can fetch it.
    """
    def handler(tu_input: dict) -> dict:
        sql_raw = tu_input.get("sql") or ""
        try:
            sql = analytics_helpers.validate_athena_sql(sql_raw, org_id)
        except analytics_helpers.SqlValidationError as e:
            return {
                "error": e.message,
                "code": e.code,
                "sql": sql_raw,
            }
        try:
            result = analytics_helpers.run_athena_query(sql, org_id)
        except analytics_helpers.AthenaQueryError as e:
            return {
                "error": e.message,
                "code": "ATHENA_ERROR",
                "sql": sql,
            }

        columns = result["columns"]
        rows_positional = result["rows"]
        rows_dicts = _positional_rows_to_dicts(columns, rows_positional)

        s3_key = None
        full_payload = {
            "sql": sql,
            "columns": columns,
            "rows": rows_positional,
            "row_count": result["row_count"],
        }
        if _approx_json_size(full_payload) > SPILL_THRESHOLD_BYTES and spill is not None:
            s3_key = spill(
                json.dumps(full_payload, default=str).encode("utf-8"),
                "run_sql.json",
            )

        run_id = cache.put(
            "sql",
            columns=columns,
            rows=rows_dicts,
            meta={"sql": sql, "s3_key": s3_key},
        )

        return {
            "run_id": run_id,
            "sql": sql,
            "columns": columns,
            "preview_rows": rows_positional[:PREVIEW_ROWS],
            "row_count": result["row_count"],
            "note": (
                f"Full {result['row_count']} rows cached under "
                f"run_id={run_id!r}; pass `from_run_id` to extract_from_rows "
                f"or aggregate."
            ),
        }
    return handler


def make_extract_from_rows_handler(
    extractor: Callable[[str, dict], str],
    cache: RunCache,
    max_workers: int = 10,
    spill: Optional[Callable[[bytes, str], str]] = None,
) -> Callable:
    """Build the extract_from_rows tool handler.

    Accepts EITHER `from_run_id` (preferred, pulls rows from cache) or a
    literal `rows` array (fallback for small ad-hoc data). Stores its
    own result under a new run_id so the agent can chain into aggregate
    without copying.

    extractor(question, row_payload) -> extracted_value str. Defaults to
    admin_api._deep_extract_for_row when wired by the worker. Wrapped
    here in a thread pool so a 100-row call doesn't serialize Bedrock
    latency.
    """
    def handler(tu_input: dict) -> dict:
        question = tu_input.get("question") or ""
        from_run_id = tu_input.get("from_run_id")

        if not isinstance(question, str) or not question.strip():
            return {"error": "question is required", "code": "BAD_INPUT"}

        if from_run_id:
            run = cache.get(from_run_id)
            if run is None:
                return {
                    "error": (
                        f"Unknown run_id {from_run_id!r}. Use the run_id "
                        f"returned by your most recent run_sql call."
                    ),
                    "code": "UNKNOWN_RUN_ID",
                }
            rows = run["rows"]
            source_columns = run["columns"]
        else:
            rows = tu_input.get("rows") or []
            if not isinstance(rows, list):
                return {"error": "rows must be a list", "code": "BAD_INPUT"}
            if len(rows) == 0:
                return {
                    "error": (
                        "No rows provided. Pass `from_run_id` with the "
                        "run_id from your run_sql call (preferred), or a "
                        "literal `rows` array of column-keyed objects."
                    ),
                    "code": "EMPTY_ROWS",
                }
            source_columns = None  # not known for ad-hoc literal rows

        if len(rows) > MAX_EXTRACT_ROWS:
            return {
                "error": (
                    f"extract_from_rows received {len(rows)} rows; cap is "
                    f"{MAX_EXTRACT_ROWS}. Narrow the scope and call again."
                ),
                "code": "TOO_MANY_ROWS",
            }

        extracted: list = [None] * len(rows)
        with ThreadPoolExecutor(max_workers=max_workers) as pool:
            futures = {
                pool.submit(extractor, question, row if isinstance(row, dict) else {}): i
                for i, row in enumerate(rows)
            }
            for fut in futures:
                idx = futures[fut]
                try:
                    extracted[idx] = fut.result()
                except Exception as e:
                    extracted[idx] = f"error: {type(e).__name__}"

        # Preserve EVERY source-row field next to extracted_value. Without
        # this, "show clientvisit_id alongside its extracted agency" is
        # unreachable through the tool catalog and the agent wastes turns
        # trying to encode joins into the extraction prompt. With it, the
        # extract run_id already carries everything finalize/select_columns
        # need — no merge tool required.
        result_rows = []
        for i, (src, value) in enumerate(zip(rows, extracted)):
            entry = {"row_index": i}
            if isinstance(src, dict):
                entry.update(src)
            entry["extracted_value"] = value
            result_rows.append(entry)

        # Build the column list: row_index first, then the source columns
        # in their original order, then extracted_value. Prefer the cached
        # source_columns when available (came from run_sql via from_run_id);
        # otherwise walk the first row's keys.
        src_col_names: list = []
        if source_columns:
            for c in source_columns:
                name = c.get("name") if isinstance(c, dict) else str(c)
                if name and name not in src_col_names:
                    src_col_names.append(name)
        else:
            for row in rows:
                if isinstance(row, dict):
                    for k in row.keys():
                        if k not in src_col_names:
                            src_col_names.append(k)
                    break
        result_columns = [{"name": "row_index", "type": "number"}]
        result_columns += [{"name": k, "type": "string"} for k in src_col_names]
        result_columns.append({"name": "extracted_value", "type": "string"})

        # Spill the full extract for very large results so the cache doesn't
        # balloon — but we still keep the dict rows in cache so downstream
        # tools can use them by run_id.
        s3_key = None
        if _approx_json_size({"results": result_rows}) > SPILL_THRESHOLD_BYTES and spill is not None:
            s3_key = spill(
                json.dumps({"results": result_rows}, default=str).encode("utf-8"),
                "extract.json",
            )

        run_id = cache.put(
            "extract",
            columns=result_columns,
            rows=result_rows,
            meta={"question": question, "source_columns": source_columns, "s3_key": s3_key},
        )

        return {
            "run_id": run_id,
            "row_count": len(result_rows),
            "preview_results": result_rows[:PREVIEW_ROWS],
            "note": (
                f"Extracted {len(result_rows)} values; cached under "
                f"run_id={run_id!r}. Each row preserves ALL source "
                f"columns ({', '.join(src_col_names) or '(none)'}) plus "
                f"`extracted_value` — so you can: pass `from_run_id` to "
                f"aggregate (e.g. group_by=['extracted_value']), or pass "
                f"it to select_columns to pick a final shape, or pass it "
                f"straight to finalize. NEVER try to merge the extraction "
                f"back to a separate run_id — it's already merged."
            ),
        }
    return handler


def _aggregate_impl(rows: list, group_by: list, agg: str,
                    sum_field: Optional[str], order_by: str) -> dict:
    """Pure in-memory group_by + count/sum. Returns positional rows."""
    buckets: dict = {}
    for row in rows:
        if not isinstance(row, dict):
            continue
        key = tuple(str(row.get(k, "")) for k in group_by)
        bucket = buckets.setdefault(key, {"count": 0, "sum": 0.0})
        bucket["count"] += 1
        if agg == "sum":
            try:
                bucket["sum"] += float(row.get(sum_field, 0) or 0)
            except (TypeError, ValueError):
                pass

    value_col = "count" if agg == "count" else f"sum_{sum_field}"
    columns = [{"name": k, "type": "string"} for k in group_by] + [
        {"name": value_col, "type": "number"}
    ]
    out_rows = []
    for key, bucket in buckets.items():
        value = bucket["count"] if agg == "count" else bucket["sum"]
        out_rows.append(list(key) + [value])

    if order_by == "count_desc":
        out_rows.sort(key=lambda r: r[-1], reverse=True)
    elif order_by == "count_asc":
        out_rows.sort(key=lambda r: r[-1])
    elif order_by == "key_asc":
        out_rows.sort(key=lambda r: r[: len(group_by)])

    return {"columns": columns, "rows": out_rows, "row_count": len(out_rows)}


def make_aggregate_handler(cache: RunCache) -> Callable:
    """Build the aggregate tool handler. Accepts either `from_run_id`
    (pulls rows from cache) or a literal `rows` array. Stashes its own
    result under a new run_id so the agent can pass it to finalize by id
    if desired (though for typical small aggregate results, inlining is fine).
    """
    def handler(tu_input: dict) -> dict:
        group_by = tu_input.get("group_by") or []
        agg = tu_input.get("agg") or "count"
        sum_field = tu_input.get("sum_field")
        order_by = tu_input.get("order_by") or "count_desc"
        from_run_id = tu_input.get("from_run_id")

        if not isinstance(group_by, list) or not group_by:
            return {"error": "group_by must be a non-empty list", "code": "BAD_INPUT"}
        if agg == "sum" and not sum_field:
            return {"error": "agg='sum' requires sum_field", "code": "BAD_INPUT"}

        if from_run_id:
            run = cache.get(from_run_id)
            if run is None:
                return {
                    "error": (
                        f"Unknown run_id {from_run_id!r}. Use the run_id "
                        f"returned by your most recent run_sql or "
                        f"extract_from_rows call."
                    ),
                    "code": "UNKNOWN_RUN_ID",
                }
            rows = run["rows"]
        else:
            rows = tu_input.get("rows") or []
            if not isinstance(rows, list):
                return {"error": "rows must be a list", "code": "BAD_INPUT"}
            if len(rows) == 0:
                return {
                    "error": (
                        "No rows. Pass `from_run_id` from a prior run_sql "
                        "or extract_from_rows call, or a literal `rows` array."
                    ),
                    "code": "EMPTY_ROWS",
                }

        result = _aggregate_impl(rows, group_by, agg, sum_field, order_by)
        run_id = cache.put(
            "agg",
            columns=result["columns"],
            rows=_positional_rows_to_dicts(result["columns"], result["rows"]),
            meta={"group_by": group_by, "agg": agg},
        )
        return {
            "run_id": run_id,
            "columns": result["columns"],
            "rows": result["rows"],
            "row_count": result["row_count"],
        }
    return handler


# Back-compat alias for tests that imported the old function directly.
def aggregate_handler(tu_input: dict) -> dict:
    """Legacy literal-rows aggregate. Prefer make_aggregate_handler() with
    a RunCache for the agent-loop path; this remains for unit tests and
    any caller that just wants pure aggregation."""
    rows = tu_input.get("rows") or []
    group_by = tu_input.get("group_by") or []
    agg = tu_input.get("agg") or "count"
    sum_field = tu_input.get("sum_field")
    order_by = tu_input.get("order_by") or "count_desc"
    if not isinstance(rows, list):
        return {"error": "rows must be a list", "code": "BAD_INPUT"}
    if not isinstance(group_by, list) or not group_by:
        return {"error": "group_by must be a non-empty list", "code": "BAD_INPUT"}
    if agg == "sum" and not sum_field:
        return {"error": "agg='sum' requires sum_field", "code": "BAD_INPUT"}
    return _aggregate_impl(rows, group_by, agg, sum_field, order_by)


# ---- filter_rows handler ----------------------------------------------

_FILTER_ROWS_VALID_OPS = ("==", "!=", "is_null", "is_not_null", "in", "not_in")


def make_filter_rows_handler(cache: RunCache) -> Callable:
    """Build the filter_rows tool handler.

    Drops rows from a cached run based on a single-column predicate. The
    surviving rows are cached under a new run_id and also returned inline
    in positional shape so finalize can consume it directly.

    Exists because the agent has no other way to narrow a cached extract
    result — run_sql can't reference run_ids and select_columns only
    projects columns, not rows. Without this tool the agent ends up
    encoding row-filtering inside extract_from_rows prompts, which is
    fragile and wastes a Bedrock call per row.
    """
    def handler(tu_input: dict) -> dict:
        from_run_id = tu_input.get("from_run_id")
        field = tu_input.get("field")
        op = tu_input.get("op")
        value = tu_input.get("value")
        values = tu_input.get("values")

        if not from_run_id:
            return {"error": "from_run_id is required", "code": "BAD_INPUT"}
        if not field or not isinstance(field, str):
            return {"error": "field is required", "code": "BAD_INPUT"}
        if op not in _FILTER_ROWS_VALID_OPS:
            return {
                "error": (
                    f"op must be one of {_FILTER_ROWS_VALID_OPS}, got {op!r}"
                ),
                "code": "BAD_INPUT",
            }
        if op in ("in", "not_in"):
            if not isinstance(values, list) or len(values) == 0:
                return {
                    "error": f"op={op!r} requires non-empty `values` list",
                    "code": "BAD_INPUT",
                }
        elif op in ("==", "!="):
            if value is None:
                return {
                    "error": f"op={op!r} requires `value`",
                    "code": "BAD_INPUT",
                }

        run = cache.get(from_run_id)
        if run is None:
            return {
                "error": (
                    f"Unknown run_id {from_run_id!r}. Use the run_id "
                    f"returned by a previous tool."
                ),
                "code": "UNKNOWN_RUN_ID",
            }
        src_rows = run["rows"]
        src_columns = run.get("columns") or []

        # Validate the field exists. Match the leniency of select_columns:
        # use the declared columns plus any keys actually present on row 0.
        src_col_names = {
            (c.get("name") if isinstance(c, dict) else str(c))
            for c in src_columns
        }
        if src_rows and isinstance(src_rows[0], dict):
            src_col_names |= set(src_rows[0].keys())
        if field not in src_col_names:
            return {
                "error": (
                    f"Unknown field {field!r}. Known fields: "
                    f"{sorted(src_col_names)}."
                ),
                "code": "UNKNOWN_COLUMN",
            }

        target_str = str(value) if value is not None else None
        values_str = [str(v) for v in values] if isinstance(values, list) else []
        values_set = set(values_str)

        def keep(row: dict) -> bool:
            actual = row.get(field, None)
            if op == "is_null":
                return actual is None or actual == ""
            if op == "is_not_null":
                return actual is not None and actual != ""
            actual_str = str(actual) if actual is not None else ""
            if op == "==":
                return actual_str == target_str
            if op == "!=":
                return actual_str != target_str
            if op == "in":
                return actual_str in values_set
            if op == "not_in":
                return actual_str not in values_set
            return False

        kept_rows = [r for r in src_rows if isinstance(r, dict) and keep(r)]

        # Preserve the source's column list verbatim so downstream tools
        # (aggregate, select_columns, finalize) see the same shape.
        out_columns = list(src_columns)
        out_col_names = [
            (c.get("name") if isinstance(c, dict) else str(c)) for c in out_columns
        ]
        positional_rows = [
            [r.get(name, "") for name in out_col_names] for r in kept_rows
        ]

        run_id = cache.put(
            "filter",
            columns=out_columns,
            rows=kept_rows,
            meta={"from_run_id": from_run_id, "field": field, "op": op},
        )
        return {
            "run_id": run_id,
            "columns": out_columns,
            "rows": positional_rows[:PREVIEW_ROWS],
            "row_count": len(kept_rows),
            "note": (
                f"Filtered {len(src_rows)} -> {len(kept_rows)} rows under "
                f"run_id={run_id!r}. Columns unchanged from source."
            ),
        }
    return handler


# ---- select_columns handler -------------------------------------------

_SELECT_COLUMNS_VALID_OPS = ("==", "!=")


def make_select_columns_handler(cache: RunCache) -> Callable:
    """Build the select_columns tool handler.

    Picks a subset of columns from the rows behind a run_id, with optional
    per-column CASE-WHEN substitution. The result is cached under a new
    run_id and also returned inline in positional shape so finalize can
    consume it directly.

    Supported `computed[col]` shape:
        {"case_when": {
            "field": <source_col>,
            "op": "==" | "!=",
            "value": <literal>,
            "then": <literal_str OR source_col_name>,
            "else": <literal_str OR source_col_name>,
        }}
    `then` / `else` are looked up as source columns when their string
    matches a source column name; otherwise treated as literals. This
    lets the agent express "show answer when extracted_value == UNKNOWN,
    else empty string" without any procedural code.
    """
    def handler(tu_input: dict) -> dict:
        from_run_id = tu_input.get("from_run_id")
        out_cols = tu_input.get("columns") or []
        computed = tu_input.get("computed") or {}

        if not from_run_id:
            return {
                "error": "from_run_id is required",
                "code": "BAD_INPUT",
            }
        if not isinstance(out_cols, list) or not out_cols:
            return {
                "error": "columns must be a non-empty list of names",
                "code": "BAD_INPUT",
            }
        if not isinstance(computed, dict):
            return {
                "error": "computed must be an object",
                "code": "BAD_INPUT",
            }

        run = cache.get(from_run_id)
        if run is None:
            return {
                "error": (
                    f"Unknown run_id {from_run_id!r}. Use the run_id "
                    f"returned by a previous tool."
                ),
                "code": "UNKNOWN_RUN_ID",
            }
        src_rows = run["rows"]
        src_col_names = {
            (c.get("name") if isinstance(c, dict) else str(c))
            for c in (run.get("columns") or [])
        }
        # Source-row keys actually present (some rows may carry extras the
        # source columns list missed — be lenient).
        if src_rows and isinstance(src_rows[0], dict):
            src_col_names |= set(src_rows[0].keys())

        # Validate every output column resolves either to a source column
        # or to a computed entry — fail fast with a helpful message.
        unresolved = [
            c for c in out_cols
            if c not in src_col_names and c not in computed
        ]
        if unresolved:
            return {
                "error": (
                    f"Unknown output column(s): {unresolved}. Must be "
                    f"either a source column ({sorted(src_col_names)}) "
                    f"or a key in `computed`."
                ),
                "code": "UNKNOWN_COLUMN",
            }

        # Validate each computed spec up-front so we don't crash mid-row.
        for col, spec in computed.items():
            if not isinstance(spec, dict) or "case_when" not in spec:
                return {
                    "error": (
                        f"computed[{col!r}] must be {{case_when: {{...}}}}"
                    ),
                    "code": "BAD_COMPUTED",
                }
            cw = spec["case_when"]
            for k in ("field", "op", "value", "then", "else"):
                if k not in cw:
                    return {
                        "error": (
                            f"computed[{col!r}].case_when missing key {k!r}"
                        ),
                        "code": "BAD_COMPUTED",
                    }
            if cw["op"] not in _SELECT_COLUMNS_VALID_OPS:
                return {
                    "error": (
                        f"computed[{col!r}].case_when.op must be one of "
                        f"{_SELECT_COLUMNS_VALID_OPS}, got {cw['op']!r}"
                    ),
                    "code": "BAD_COMPUTED",
                }

        def _resolve(value_or_colname, row: dict):
            """If value_or_colname matches a source column name, return
            the row's value for that column; otherwise return it as a
            literal string."""
            if isinstance(value_or_colname, str) and value_or_colname in src_col_names:
                return row.get(value_or_colname, "")
            return value_or_colname

        def _eval_case(spec: dict, row: dict):
            cw = spec["case_when"]
            actual = row.get(cw["field"], None)
            target = cw["value"]
            matches = (str(actual) == str(target)) if cw["op"] == "==" else (str(actual) != str(target))
            return _resolve(cw["then"] if matches else cw["else"], row)

        # Project the rows.
        positional_rows = []
        dict_rows = []
        for row in src_rows:
            if not isinstance(row, dict):
                continue
            picked = {}
            for c in out_cols:
                if c in computed:
                    picked[c] = _eval_case(computed[c], row)
                else:
                    picked[c] = row.get(c, "")
            dict_rows.append(picked)
            positional_rows.append([picked[c] for c in out_cols])

        out_columns = [{"name": c, "type": "string"} for c in out_cols]
        run_id = cache.put(
            "select",
            columns=out_columns,
            rows=dict_rows,
            meta={"from_run_id": from_run_id, "computed_keys": list(computed.keys())},
        )
        return {
            "run_id": run_id,
            "columns": out_columns,
            "rows": positional_rows,
            "row_count": len(positional_rows),
        }
    return handler


# ---- concat_runs handler ----------------------------------------------

def make_concat_runs_handler(cache: RunCache) -> Callable:
    """Build the concat_runs tool handler. UNION ALL the rows from multiple
    cached runs into a new cached run.

    Strict column-set match: all inputs must share the same set of column
    names (order-insensitive — rows are dict-keyed). Mismatched columns
    are almost always an agent mistake (concatenating an extract with a
    raw run_sql, say), and silently lining them up would produce a
    nonsensical final table.
    """
    def handler(tu_input: dict) -> dict:
        ids = tu_input.get("from_run_ids") or []
        if not isinstance(ids, list) or len(ids) < 2:
            return {
                "error": "from_run_ids must be a list of >= 2 run_ids",
                "code": "BAD_INPUT",
            }

        runs = []
        for rid in ids:
            run = cache.get(rid)
            if run is None:
                return {
                    "error": (
                        f"Unknown run_id {rid!r} in from_run_ids. "
                        f"Use run_ids returned by previous tool calls."
                    ),
                    "code": "UNKNOWN_RUN_ID",
                }
            runs.append((rid, run))

        # Validate column-set match. We compare by name only — types
        # aren't checked because everything's string-typed in our schema.
        col_sets = [
            frozenset(
                (c.get("name") if isinstance(c, dict) else str(c))
                for c in (run.get("columns") or [])
            )
            for _, run in runs
        ]
        if len(set(col_sets)) > 1:
            return {
                "error": (
                    f"Column sets differ across run_ids; concat_runs "
                    f"requires identical column names. "
                    + ", ".join(
                        f"{rid}={sorted(cs)}"
                        for (rid, _), cs in zip(runs, col_sets)
                    )
                ),
                "code": "COLUMN_MISMATCH",
            }

        combined_rows = []
        for _, run in runs:
            combined_rows.extend(run.get("rows") or [])

        # Use the first run's column list as canonical (order is preserved
        # from there). Drop row_index since it's no longer globally unique.
        first_cols = list(runs[0][1].get("columns") or [])
        first_cols = [
            c for c in first_cols
            if (c.get("name") if isinstance(c, dict) else str(c)) != "row_index"
        ]
        # Also drop row_index from each combined row, then re-emit it.
        for r in combined_rows:
            if isinstance(r, dict) and "row_index" in r:
                del r["row_index"]
        for i, r in enumerate(combined_rows):
            if isinstance(r, dict):
                r["row_index"] = i
        out_columns = [{"name": "row_index", "type": "number"}] + first_cols

        run_id = cache.put(
            "concat",
            columns=out_columns,
            rows=combined_rows,
            meta={"source_run_ids": ids},
        )
        return {
            "run_id": run_id,
            "columns": out_columns,
            "row_count": len(combined_rows),
            "note": (
                f"Concatenated {len(ids)} runs ({', '.join(ids)}) into "
                f"{len(combined_rows)} rows under run_id={run_id!r}. "
                f"Pass `from_run_id` to aggregate / select_columns / finalize."
            ),
        }
    return handler


# ---- S3 spill helper --------------------------------------------------

def org_data_bucket(org_id: str) -> str:
    """Bucket name for an org's data + analytics results.

    Mirrors infra/components/analytics.py:`f"{PROJECT_NAME}-{org_id}"`.
    Agent intermediate payloads include scoped chart rows (derivative PHI),
    so they must stay inside the same compliance boundary as Athena's
    `athena-results/` output — i.e. the org's own bucket, never a shared
    one.
    """
    return f"penguin-health-{org_id}"


def make_s3_spill(s3_client, bucket: str, job_id: str,
                  *, org_id: Optional[str] = None) -> Callable[[bytes, str], str]:
    """Return a spill(bytes, suffix_hint) -> s3_key function for one job.

    Writes to `agent-io/{job_id}/{ts}-{rand}-{hint}` in the given bucket.
    The `agent-io/` prefix is parallel to `athena-results/`; operators
    should apply a lifecycle rule on `agent-io/` matching the DynamoDB
    job TTL (24h) so spilled payloads expire alongside the job item that
    references them.

    When `org_id` is provided, emits one s3_write audit event per spill so
    the analytics-result payload (derivative PHI) has the same audit
    coverage as primary data writes. `org_id` is keyword-only for
    backwards compatibility with existing call sites — callers without
    org_id get the legacy un-audited behavior, which is acceptable only
    for tests.
    """
    bucket_org = org_id or bucket.removeprefix("penguin-health-")

    def spill(data: bytes, suffix_hint: str) -> str:
        key = f"agent-io/{job_id}/{int(time.time() * 1000)}-{uuid.uuid4().hex[:8]}-{suffix_hint}"
        s3_client.put_object(Bucket=bucket, Key=key, Body=data, ContentType="application/json")
        audit_emit(
            action='write',
            resource={'type': 'S3Object', 'id': f's3://{bucket}/{key}',
                      'org': bucket_org},
            actor=_AUDIT_PRINCIPAL.as_actor(),
            org_id=bucket_org,
            purpose_of_use='ANALYTICS',
            call_type='s3_write',
            external_control_number=job_id,
        )
        return key
    return spill


# ---- Misc -------------------------------------------------------------

def _approx_json_size(obj) -> int:
    """Estimate JSON-encoded size in bytes without holding two full copies."""
    try:
        return len(json.dumps(obj, default=str).encode("utf-8"))
    except Exception:
        return 0


def make_tool_handlers(
    *,
    org_id: str,
    extractor: Callable[[str, dict], str],
    cache: Optional[RunCache] = None,
    spill: Optional[Callable[[bytes, str], str]] = None,
) -> dict:
    """Convenience wiring used by the worker; tests can build their own.

    The RunCache is the shared scratch space for `run_id` handoffs between
    tools. The worker creates one per agent invocation and passes it in
    so the cache lives only for the duration of that one run.
    """
    if cache is None:
        cache = RunCache()
    return {
        "inspect_schema": make_inspect_schema_handler(org_id),
        "run_sql": make_run_sql_handler(org_id, cache=cache, spill=spill),
        "extract_from_rows": make_extract_from_rows_handler(
            extractor, cache=cache, spill=spill,
        ),
        "aggregate": make_aggregate_handler(cache),
        "filter_rows": make_filter_rows_handler(cache),
        "select_columns": make_select_columns_handler(cache),
        "concat_runs": make_concat_runs_handler(cache),
    }


